import { Repository } from "@/types";

function generateStarHistory(currentStars: number, gained: number): { date: string; stars: number }[] {
  const points = 12;
  const history: { date: string; stars: number }[] = [];
  const baseStars = currentStars - gained * 2;
  for (let i = 0; i < points; i++) {
    const d = new Date();
    d.setMonth(d.getMonth() - (points - 1 - i));
    const progress = i / (points - 1);
    const noise = Math.floor(Math.random() * gained * 0.1);
    history.push({
      date: `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}`,
      stars: Math.floor(baseStars + (currentStars - baseStars) * (progress ** 1.3) + noise),
    });
  }
  history[history.length - 1].stars = currentStars;
  return history;
}

export const MOCK_REPOS: Repository[] = [
  {
    id: 1,
    github_id: 100001,
    full_name: "openai/codex",
    description:
      "Lightweight coding agent that runs in your terminal, understands your codebase, and helps you ship faster.",
    language: "TypeScript",
    stars: 24500,
    forks: 2100,
    open_issues: 342,
    created_at: "2025-01-15T00:00:00Z",
    updated_at: "2026-05-04T00:00:00Z",
    pushed_at: "2026-05-04T00:00:00Z",
    license: "Apache-2.0",
    topics: ["ai", "coding-assistant", "cli", "developer-tools"],
    size: 45000,
    homepage_url: "https://openai.com/codex",
    archived: false,
    fork: false,
    stars_gained: 1850,
    health_score: 92,
    friendliness_score: 78,
    maturity_score: 75,
    trending_score: 95,
    good_first_issue_count: 23,
    has_contributing: true,
    pr_merge_rate: 0.72,
    avg_issue_response_hours: 8,
    star_history: generateStarHistory(24500, 1850),
  },
  {
    id: 2,
    github_id: 100002,
    full_name: "astral-sh/uv",
    description:
      "An extremely fast Python package and project manager, written in Rust.",
    language: "Rust",
    stars: 58000,
    forks: 3200,
    open_issues: 456,
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2026-05-05T00:00:00Z",
    pushed_at: "2026-05-05T00:00:00Z",
    license: "MIT",
    topics: ["python", "package-manager", "rust", "fast"],
    size: 120000,
    homepage_url: "https://docs.astral.sh/uv/",
    archived: false,
    fork: false,
    stars_gained: 1200,
    health_score: 96,
    friendliness_score: 65,
    maturity_score: 88,
    trending_score: 88,
    good_first_issue_count: 15,
    has_contributing: true,
    pr_merge_rate: 0.85,
    avg_issue_response_hours: 4,
    star_history: generateStarHistory(58000, 1200),
  },
  {
    id: 3,
    github_id: 100003,
    full_name: "EbookFoundation/free-programming-books",
    description: "Freely available programming books",
    language: null,
    stars: 345000,
    forks: 62000,
    open_issues: 34,
    created_at: "2013-10-11T00:00:00Z",
    updated_at: "2026-05-05T00:00:00Z",
    pushed_at: "2026-05-04T00:00:00Z",
    license: "CC-BY-4.0",
    topics: ["books", "education", "free", "programming"],
    size: 8000,
    homepage_url: null,
    archived: false,
    fork: false,
    stars_gained: 450,
    health_score: 70,
    friendliness_score: 95,
    maturity_score: 99,
    trending_score: 60,
    good_first_issue_count: 8,
    has_contributing: true,
    pr_merge_rate: 0.91,
    avg_issue_response_hours: 12,
    star_history: generateStarHistory(345000, 450),
  },
  {
    id: 4,
    github_id: 100004,
    full_name: "pocketbase/pocketbase",
    description:
      "Open Source realtime backend in 1 file — Go + SQLite + Vue admin UI",
    language: "Go",
    stars: 42000,
    forks: 2000,
    open_issues: 89,
    created_at: "2022-07-05T00:00:00Z",
    updated_at: "2026-05-03T00:00:00Z",
    pushed_at: "2026-05-03T00:00:00Z",
    license: "MIT",
    topics: ["backend", "database", "go", "realtime", "self-hosted"],
    size: 95000,
    homepage_url: "https://pocketbase.io",
    archived: false,
    fork: false,
    stars_gained: 780,
    health_score: 85,
    friendliness_score: 58,
    maturity_score: 82,
    trending_score: 76,
    good_first_issue_count: 5,
    has_contributing: true,
    pr_merge_rate: 0.45,
    avg_issue_response_hours: 24,
    star_history: generateStarHistory(42000, 780),
  },
  {
    id: 5,
    github_id: 100005,
    full_name: "shadcn-ui/ui",
    description:
      "A set of beautifully-designed, accessible components and a code distribution platform.",
    language: "TypeScript",
    stars: 82000,
    forks: 5500,
    open_issues: 1200,
    created_at: "2023-01-04T00:00:00Z",
    updated_at: "2026-05-05T00:00:00Z",
    pushed_at: "2026-05-05T00:00:00Z",
    license: "MIT",
    topics: ["react", "tailwindcss", "components", "ui", "accessibility"],
    size: 200000,
    homepage_url: "https://ui.shadcn.com",
    archived: false,
    fork: false,
    stars_gained: 920,
    health_score: 88,
    friendliness_score: 72,
    maturity_score: 90,
    trending_score: 82,
    good_first_issue_count: 32,
    has_contributing: true,
    pr_merge_rate: 0.68,
    avg_issue_response_hours: 18,
    star_history: generateStarHistory(82000, 920),
  },
  {
    id: 6,
    github_id: 100006,
    full_name: "juspay/hyperswitch",
    description:
      "An open source payments switch written in Rust to make payments fast, reliable and affordable.",
    language: "Rust",
    stars: 15000,
    forks: 1800,
    open_issues: 245,
    created_at: "2022-09-15T00:00:00Z",
    updated_at: "2026-05-05T00:00:00Z",
    pushed_at: "2026-05-05T00:00:00Z",
    license: "Apache-2.0",
    topics: ["payments", "rust", "fintech", "open-source"],
    size: 180000,
    homepage_url: "https://hyperswitch.io",
    archived: false,
    fork: false,
    stars_gained: 340,
    health_score: 90,
    friendliness_score: 88,
    maturity_score: 78,
    trending_score: 65,
    good_first_issue_count: 45,
    has_contributing: true,
    pr_merge_rate: 0.82,
    avg_issue_response_hours: 6,
    star_history: generateStarHistory(15000, 340),
  },
  {
    id: 7,
    github_id: 100007,
    full_name: "maybe-finance/maybe",
    description:
      "The OS for your personal finances — budgeting, wealth management, financial planning.",
    language: "Ruby",
    stars: 38000,
    forks: 2800,
    open_issues: 156,
    created_at: "2024-01-17T00:00:00Z",
    updated_at: "2026-05-04T00:00:00Z",
    pushed_at: "2026-05-04T00:00:00Z",
    license: "MIT",
    topics: ["finance", "budgeting", "self-hosted", "ruby-on-rails"],
    size: 65000,
    homepage_url: "https://maybe.co",
    archived: false,
    fork: false,
    stars_gained: 520,
    health_score: 82,
    friendliness_score: 74,
    maturity_score: 72,
    trending_score: 70,
    good_first_issue_count: 18,
    has_contributing: true,
    pr_merge_rate: 0.76,
    avg_issue_response_hours: 14,
    star_history: generateStarHistory(38000, 520),
  },
  {
    id: 8,
    github_id: 100008,
    full_name: "biomejs/biome",
    description:
      "A toolchain for web projects — format, lint, and more in a fraction of a second.",
    language: "Rust",
    stars: 16500,
    forks: 520,
    open_issues: 312,
    created_at: "2023-07-27T00:00:00Z",
    updated_at: "2026-05-05T00:00:00Z",
    pushed_at: "2026-05-05T00:00:00Z",
    license: "MIT",
    topics: ["formatter", "linter", "rust", "javascript", "typescript"],
    size: 140000,
    homepage_url: "https://biomejs.dev",
    archived: false,
    fork: false,
    stars_gained: 290,
    health_score: 94,
    friendliness_score: 82,
    maturity_score: 76,
    trending_score: 62,
    good_first_issue_count: 28,
    has_contributing: true,
    pr_merge_rate: 0.79,
    avg_issue_response_hours: 10,
    star_history: generateStarHistory(16500, 290),
  },
];
